---

- name: Install Visual Studio Code extensions
  command: code --install-extension {{ item }}
  with_items:
    - formulahendry.auto-close-tag
    - karunamurti.haml
    - kamasamak.vscode-cfml
    - marcochavezf.darcula-operator-mono-vscode
    - peterjausovec.vscode-docker
    - eamodio.gitlens
    - orta.vscode-jest
    - christian-kohler.npm-intellisense
    - ckolkman.vscode-postgres
    - esbenp.prettier-vscode
    - rebornix.ruby
    - vayan.haml
    - castwide.solargraph
    - misogi.ruby-rubocop
    - ms-mssql.mssql
    - eg2.tslint
    - rbbit.typescript-hero
    - vscodevim.vim
    - jpoissonnier.vscode-styled-components

- name: Enable key-repeating
  command: defaults write {{ item }} -bool false
  with_items:
    - com.microsoft.VSCode ApplePressAndHoldEnabled
    - com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled

- name: Copy Visual Studio Code configurations
  copy:
    src: "{{ playbook_dir }}/dotfiles/vscode/{{ item }}"
    dest: "~/Library/Application\ Support/Code/User/{{ item }}"
  with_items:
    - keybindings.json
    - settings.json

- name: Prepare Neovim directories
  file: path=~/.config/nvim/bundle state=directory

- name: Copy Neovim configuration
  copy:
    src: "{{ playbook_dir }}/dotfiles/init.vim"
    dest: ~/.config/nvim/init.vim

- name: Install Vundle for Neovim
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.config/nvim/bundle/Vundle.vim