---

- hosts: localhost
  vars:
    home: "/Users/{{ lookup('env', 'USER') }}"
    user: "{{ lookup('env', 'USER' )}}"
    ssh_private_key: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY') }}"
    ssh_public_key:  "{{ lookup('env', 'ANSIBLE_SSH_PUBLIC_KEY') }}"
    gpg_private_key: "{{ lookup('env', 'ANSIBLE_GPG_PRIVATE_KEY') }}"
    gpg_public_key: "{{ lookup('env', 'ANSIBLE_GPG_PUBLIC_KEY') }}"
  user: "{{ lookup('env', 'USER' )}}"
  roles:
    - check
    - brew
    - git
    - editor
    - gpg
    - ssh
    - dotfiles
