- name: Set cron shell
  cron: name=SHELL env=yes value=/bin/zsh

- name: Empty existing ZSH config
  copy:
    content: ""
    dest: ~/.zshrc
    force: true

- name: ZSH config
  lineinfile: dest=~/.zshrc line='{{ item }}'
  with_items:
    - "ZSH_TMUX_AUTOSTART=true"
    - "ZSH_TMUX_AUTOQUIT=false"
    - "source $(brew --prefix)/share/antigen/antigen.zsh"
    - "antigen bundle zsh-users/zsh-syntax-highlighting"
    - "antigen bundle zsh-users/zsh-autosuggestions"
    - "antigen theme refined"
    - "antigen bundle git"
    - "antigen bundle docker"
    - "antigen bundle vi-mode"
    - "antigen bundle urltools"
    - "antigen apply"
    - "export EDITOR=vim"
    - 'COMPLETION_WAITING_DOTS="true"'

- name: Create aliases
  lineinfile: dest=~/.zshrc line='alias {{ item.key }}=\"{{ item.value }}\"'
  with_dict: "{{ aliases }}"
  vars:
    aliases:
      findinfiles: 'grep --exclude-dir={node_modules,.git,dist,build} -irn "." -e'
      ip: "curl https://am.i.mullvad.net/connected"
      l: "ls -al"
      "..": "cd .."
      "...": "cd ..; cd .."
      "hide": "defaults write com.apple.finder CreateDesktop false; killall Finder;"
      "show": "defaults write com.apple.finder CreateDesktop true; killall Finder;"
      "mobile-api": "cd ~/Projects/Sunsama/mobile/sunsama-mobile-api/; yarn start"
      "meteor-lite": "cd ~/Projects/Sunsama/meteor/; make start-lite"
      git-archive: "git archive -o archive.zip HEAD $(git diff --name-only HEAD^)"

- name: Disable thumbnail generation
  command: qlmanage -r {{ item }}
  with_items:
    - cache
    - disablecache

- name: Nuke QuickLook thumbnail cache
  command: rm -rf $TMPDIR/../C/com.apple.QuickLook.thumbnailcache
