---
- name: Update brew daily
  cron: name="brew autoupdate" special_time="daily"
        job="/usr/local/bin/brew update"

- name: Cleanup brew
  cron: name="brew cleanup" special_time="monthly"
        job="/usr/local/bin/brew cleanup"

- name: Cleanup brew cask
  cron: name="brew cask cleanup" special_time="monthly"
        job="/usr/local/bin/brew cask cleanup"

- name: Install cask
  command: brew tap caskroom/cask

- name: Install packages from Homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - tree
    - python2
    - speedtest_cli
    - gnupg
    - pinentry-mac
    - antigen
    - heroku
    - exa
    - postgresql
    - neovim
    - tmux

- name: Install packages from Homebrew Cask
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - firefox
    - iterm2
    - vlc
    - slack
    - karabiner-elements
    - whatsapp
    - visual-studio-code
    - lastpass
    - abstract
    - tunnelblick
    - little-snitch
    - thunderbird
    - noti
    - transmission
