---
- name: Update brew daily
  cron: name="brew autoupdate" special_time="daily"
    job="/usr/local/bin/brew update"

- name: Cleanup brew
  cron: name="brew cleanup" special_time="monthly"
    job="/usr/local/bin/brew cleanup"

- name: Cleanup brew cask
  cron: name="brew cask cleanup" special_time="monthly"
    job="/usr/local/bin/brew cask cleanup"

- name: Install cask
  command: brew tap homebrew/cask

- name: Install packages from Homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - tree
    - speedtest_cli
    - gnupg
    - pinentry-mac
    - antigen
    - postgresql
    - sdl2
    - sdl2_gfx
    - sdl2_image
    - gh

- name: Install packages from Homebrew Cask
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - firefox
    - iterm2
    - vlc
    - slack
    - karabiner-elements
    - whatsapp
    - tunnelblick
    - little-snitch
    - micro-snitch
    - zoomus
    - qbittorrent
    - docker
    - mullvadvpn
    - notion
    - tor-browser
    - libreoffice
    - mega
    - keybase
    - robo-3t
    - loom
    - avast-security
    - flipper
    - reflector
    - adguard
    - bartender
    - plex
    - steam
    - 1password
    - jetbrains-toolbox
