---
- name: Update brew daily
  cron: name="brew autoupdate" special_time="daily"
        job="/usr/local/bin/brew update"

- name: Cleanup brew
  cron: name="brew cleanup" special_time="monthly"
        job="/usr/local/bin/brew cleanup"

- name: Install packages from Homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - nvm
    - tree
    - python2
    - speedtest_cli
    - neovim
    - tmux
    - gnupg
    - pinentry-mac
    - antigen
    - heroku
    - exa
    - docker
    - docker-compose
    - postgresql
    - redis
    - phantomjs

- name: Install packages from Homebrew Cask
  ignore_errors: yes
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - iterm2
    - skype
    - zoomus
    - dropbox
    - gimp
    - private-internet-access
    - slack
    - flux
    - karabiner-elements
    - bartender
    - kap
    - whatsapp
    - switchresx
    - pgadmin4
