---

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=HEAD

- name: Source nvm in ~/.zprofile
  lineinfile: >
    dest=~/.zprofile
    line="source ~/.nvm/nvm.sh"
    create=yes

- name: Install Node {{ node_version }}
  shell: source ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}

- name: Install NPM packages
  npm: name={{ item }} state=present global=yes
  with_items:
    - neovim
    - standard
    - nodemon
    - typescript
    - tslint
    - source-map-explorer
